# Generated by Django 2.0.3 on 2018-03-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dockerenv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envname', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DockerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('dockerenv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Dockerenv')),
            ],
        ),
        migrations.CreateModel(
            name='ReDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockername', models.CharField(max_length=100)),
                ('projectname', models.CharField(max_length=100)),
                ('projecturl', models.CharField(max_length=200)),
                ('projectpath', models.CharField(max_length=200)),
                ('dockerenv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Dockerenv')),
            ],
        ),
    ]
