# Generated by Django 2.0.3 on 2018-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerenv',
            name='envdescribe',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='dockerenv',
            name='envname',
            field=models.CharField(default='ynsy', max_length=100),
        ),
    ]
