# Generated by Django 2.0.3 on 2018-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180320_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerenv',
            name='envdescribe',
            field=models.TextField(default='environment describe'),
        ),
        migrations.AlterField(
            model_name='dockerenv',
            name='envname',
            field=models.CharField(default='environment name', max_length=100),
        ),
    ]
